# Generated by Django 6.0.6 on 2026-06-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('publicada', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem da galeria',
                'verbose_name_plural': 'Imagens da galeria',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Lancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('capacidade', models.PositiveIntegerField()),
                ('preco_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('MANUTENCAO', 'Em manutenção'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='lanchas/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lancha',
                'verbose_name_plural': 'Lanchas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do sistema',
                'verbose_name_plural': 'Logs do sistema',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('FUNCIONARIO', 'Funcionário'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('documento', models.CharField(blank=True, help_text='CPF ou documento de identificação', max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('quantidade_pessoas', models.PositiveIntegerField()),
                ('origem', models.CharField(choices=[('CLIENTE', 'Cliente'), ('FUNCIONARIO', 'Funcionário'), ('PRESENCIAL', 'Presencial'), ('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp')], default='CLIENTE', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_cliente', to=settings.AUTH_USER_MODEL)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_criadas', to=settings.AUTH_USER_MODEL)),
                ('lancha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.lancha')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data', '-horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('mensagem', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField()),
                ('frequencia', models.CharField(choices=[('UNICO', 'Data específica'), ('DIAS_ANTES', 'Dias antes do evento'), ('2H', 'A cada 2 horas'), ('4H', 'A cada 4 horas'), ('DIARIO', 'Diariamente')], default='UNICO', max_length=20)),
                ('dias_antes', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='core.reserva')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
                'ordering': ['data_hora'],
            },
        ),
    ]
